[package]
name = "flexi_func"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.48", features = ["full", "derive", "parsing", "extra-traits"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"

[lib]
proc-macro = true